envenomer = envenomer or {}
envenomer.type = {
  ["0"] = {
    ["name"] = "trucizna spowolniona",
    ["saved"] = "0",
    ["full"] = "0",
    ["duration"] = "2d4",
    ["note"] = "",
  },
  ["1"] = {
    ["name"] = "slaba trucizna",
    ["saved"] = "1d5",
    ["full"] = "2d10",
    ["duration"] = "2d6",
    ["note"] = "",
  },
  ["2"] = {
    ["name"] = "srednia trucizna",
    ["saved"] = "2d15",
    ["full"] = "4d35",
    ["duration"] = "2d7",
    ["note"] = "",
  },
  ["3"] = {
    ["name"] = "silna trucizna",
    ["saved"] = "4d20",
    ["full"] = "5d45",
    ["duration"] = "3d7",
    ["note"] = "",
  },
  ["4"] = {
    ["name"] = "bardzo silna trucizna",
    ["saved"] = "4d40",
    ["full"] = "5d65",
    ["duration"] = "3d8",
    ["note"] = "",
  },
  ["5"] = {
    ["name"] = "trucizna usypiajaca",
    ["saved"] = "0",
    ["full"] = "0",
    ["duration"] = "2d4",
    ["note"] = "Zmiana pozycji na spiaca.",
  },
  ["6"] = {
    ["name"] = "trucizna oslepiajaca",
    ["saved"] = "1d5",
    ["full"] = "2d15",
    ["duration"] = "2d5",
    ["note"] = "",
  },
  ["7"] = {
    ["name"] = "trucizna paralizujaca",
    ["saved"] = "3d5",
    ["full"] = "3d25",
    ["duration"] = "2d3",
    ["note"] = "",
  },
  ["8"] = {
    ["name"] = "trucizna zabijajaca",
    ["saved"] = "4d35",
    ["full"] = "0",
    ["duration"] = "2d3",
    ["note"] = "W przypadku braku mastery envenom zabija uzywajacego",
  },
  ["9"] = {
    ["name"] = "trucizna oslabiajaca sile",
    ["saved"] = "1d5",
    ["full"] = "2d5",
    ["duration"] = "2d4",
    ["note"] = "-str",
  },
  ["10"] = {
    ["name"] = "trucizna oslabiajaca obrazenia",
    ["saved"] = "1d5",
    ["full"] = "2d4",
    ["duration"] = "2d4",
    ["note"] = "-dam",
  },
  ["11"] = {
    ["name"] = "trucizna oslabiajaca celnosc",
    ["saved"] = "1d5",
    ["full"] = "2d5",
    ["duration"] = "2d4",
    ["note"] = "-hit",
  },
}
