character.str = {
	["slabiutki"] = 1,
	["slabiutka"] = 1,
	["watly"] = 2,
	["watla"] = 2,
	["slabowity"] = 3,
	["slabowita"] = 3,
	["slaby"] = 4,
	["slaba"] = 4,
	["krzepki"] = 5,
	["krzepka"] = 5,
	["silny"] = 6,
	["silna"] = 6,
	["mocny"] = 7,
	["mocna"] = 7,
	["tegi"] = 8,
	["tega"] = 8,
	["potezny"] = 9,
	["potezna"] = 9,
	["mocarny"] = 10,
	["mocarna"] = 10,
}

character.dex = {
	["nieskoordynowany"] = 1,
	["nieskoordynowana"] = 1,
	["niezreczny"] = 2,
	["niezreczna"] = 2,
	["nieporadny"] = 3,
	["nieporadna"] = 3,
	["niezgrabny"] = 4,
	["niezgrabna"] = 4,
	["sprawny"] = 5,
	["sprawna"] = 5,
	["zwinny"] = 6,
	["zwinna"] = 6,
	["zreczny"] = 7,
	["zreczna"] = 7,
	["wygimnastykowany"] = 8,
	["wygimnastykowana"] = 8,
	["gibki"] = 9,
	["gibka"] = 9,
	["akrobatyczny"] = 10,
	["akrobatyczna"] = 10,
}

character.vit = {
	["charlawy"] = 1,
	["cherlawa"] = 1,
	["rachityczny"] = 2,
	["rachityczna"] = 2,
	["chuchrowaty"] = 3,
	["chuchrowata"] = 3,
	["mizerny"] = 4,
	["mizerna"] = 4,
	["dobrze zbudowany"] = 5,
	["dobrze zbudowana"] = 5,
	["wytrzymaly"] = 6,
	["wytrzymala"] = 6,
	["twardy"] = 7,
	["twarda"] = 7,
	["zahartowany"] = 8,
	["zahartowana"] = 8,
	["muskularny"] = 9,
	["muskularna"] = 9,
	["atletyczny"] = 10,
	["atletyczna"] = 10,
}

character.int = {
	["bezmyslny"] = 1,
	["bezmyslna"] = 1,
	["tepy"] = 2,
	["tepa"] = 2,
	["prymitywny"] = 3,
	["prymitywna"] = 3,
	["ograniczony"] = 4,
	["ograniczona"] = 4,
	["pojetny"] = 5,
	["pojetna"] = 5,
	["inteligentny"] = 6,
	["inteligentna"] = 6,
	["bystry"] = 7,
	["bystra"] = 7,
	["rezolutny"] = 8,
	["rezolutna"] = 8,
	["blyskotliwy"] = 9,
	["blyskotliwa"] = 9,
	["genialny"] = 10,
	["genialna"] = 10,
}

character.wis = {
	["glupi"] = 1,
	["glupia"] = 1,
	["zacofany"] = 2,
	["zacofana"] = 2,
	["przyglupi"] = 3,
	["przyglupia"] = 3,
	["niewyksztalcony"] = 4,
	["niewyksztalcona"] = 4,
	["wyksztalcony"] = 5,
	["wyksztalcona"] = 5,
	["madry"] = 6,
	["madra"] = 6,
	["uczony"] = 7,
	["uczona"] = 7,
	["oswiecony"] = 8,
	["oswiecona"] = 8,
	["erudycyjny"] = 9,
	["erudycyjna"] = 9,
	["wszechwiedzacy"] = 10,
	["wszechwiedzaca"] = 10,
}

character.bra = {
	["thorzliwy"] = 1,
	["thorzliwa"] = 1,
	["strachliwy"] = 2,
	["strachliwa"] = 2,
	["bojazliwy"] = 3,
	["bojazliwa"] = 3,
	["niepewny"] = 4,
	["niepewna"] = 4,
	["zdecydowany"] = 5,
	["zdecydowana"] = 5,
	["odwazny"] = 6,
	["odwazna"] = 6,
	["dzielny"] = 7,
	["dzielna"] = 7,
	["nieulekly"] = 8,
	["nieulekla"] = 8,
	["nieugiety"] = 9,
	["nieugieta"] = 9,
	["nieustraszony"] = 10,
	["nieustraszona"] = 10,
}

character.name2progress = {
	["bardzo duzo"] = 0,
	["duzo"] = 1,
	["troche"] = 2,
	["niewiele"] = 3,
	["bardzo niewiele"] = 4,
}

character.progress2name = {
	[0] = "bardzo duzo",
	[1] = "duzo",
	[2] = "troche",
	[3] = "niewiele",
	[4] = "bardzo niewiele",
}
